export const SITE_META = {
  NAME: `Big Key Word`,
  URL: `https://www.bigkeyword.club/`,
  DOMAIN: `bigkeyword.club`,
  DESC: ``,
  PARENT: `Starfavor`,
};

// export const API_URL = `https://uptapapi.uptap.com/h5Game/?type=GameList&platform=uptap&token=dXB0YXBnYW1l572R56uZ55So`;
export const API_URL = `https://dev.iwantalipstick.com/api/data-20230323.json`;

// export const CHANNEL = `uptap`;
export const GAME_PATH = `https://cdn.news-global.club/playgame_new/global_000804/`;
// export const GAME_PATH = `https://uptapapi.uptap.com/h5Game/?type=Game&platform=${CHANNEL}&appid=`;

export const IMAGE_PATH = `https://cdn.iwantalipstick.com/gameicon2/`;
export const IMAGE_FORMAT = `webp`;

export const ADSENSE_ID = ``; // ca-pub-9460854678318351
export const GA_ID = ``; // G-0WT8M0YYRP

export const DEV_MODE = false; // 广告开发模式

// 是否启用广告
export const SHOW_AD = true;

// 广告ID
export const ADS_SLOT_ID = {
  HOME: ``,
  CATEGORY: ``,
  DETAIL: ``,
};

// AdX广告ID
export const SLOT_SETTINGS = {
  "n1-300x250-1": {
    unit_id: "", //"/22958941231/example.com_1037/native1_300x250_1037_01"
    sizes: [300, 250], //
    slot_id: ``, //div-gpt-ad-1705632386565104-0
  },
};
export const EXCLUDED_GAMES = [];
export const SELECTED_GAMES = [
  "BigSword",
  "BoardTheTrain",
  "FireTheGun",
  "MergeGuns3D",
  "FeverRacing",
  "ColorBall3D",
  "ZombieSurvival",
  "CrazyMoto",
  "CrazyKart3D",
  "LetMeIn",
  "BumbleShooter",
  "Knife",
  "HiTaxi",
  "TrafficRun",
  "BulletMaster3D",
  "MrRacer",
  "MagicParkour",
  "FrozenMagic",
  "MrBullet",
  "JumpSmash",
  "CrazyKnife",
  "TrafficPassing",
  "SuperThrow",
  "AceMan",
  "BatterKing",
  "GoldenGlove",
  "KnockBalls",
  "CrashTower3D",
  "DragonCrush",
  "HungryAnimals",
  "SnakeGo",
  "DessertConnect",
  "SwiftRider",
  "CrackShot",
  "CrazyGunfight",
  "ColorRing",
  "PianoKeys",
  "ArchersKing",
  "MyBabyCare",
  "DartsKing3D",
  "CrazyRace",
  "BallIsComing",
  "HungyBunny",
  "TheSameWorld",
  "SuperMiner",
  "BounceShooter",
  "HillRacing",
  "BlockGun3D",
  "FruitMonster",
  "FierceCity",
  "IronAttack",
  "AirBrawl",
  "AmazingRoad",
  "RainbowSplash",
  "CrazyDrift",
  "FruitsFall",
  "RocketJump",
  "MagicPaint",
  "GlidingCharger",
  "RoadCharger",
  "ArcheryMaster",
  "UltraDrift",
  "SharkIsComing",
  "PuppyRun",
  "PenguinDash",
  "MonsterCrash",
  "DeathJump",
  "HungryMonster",
  "JumpingMonkey",
  "MergeKill",
  "CrazyTrain3D",
  "CrazyHammer",
  "VirusWar",
  "TrappedPirate",
  "StickmanVsZombies",
  "FingerCannon",
  "BulletMan",
  "GunShooter",
  "TowerBlast3D",
  "ShootSmash",
  "ShootingCubes",
  "BubbleBlast",
  "FlyPass",
  "KillAllZombies",
  "CollectColorfulBalls",
  "KimbapRun",
  "AnipopLink",
  "PetsMatch",
  "HappyBilliards",
  "CrazyBomb",
  "HelpTheZombie",
  "SaveThePets",
  "SoccerHero",
  "TableTennisChampionship",
  "MagicDonuts",
  "SolitaireClassic",
  "DeathRun",
  "IdleRestaurantTycoon",
  "ImEmpire",
  "MahjongConnect",
  "MiningMaster",
  "Transform",
  "DefenseTower",
  "TwistyRoad",
  "ZooBlast",
  "ZumaMarbles",
  "BlockPuzzle",
  "CrazyPortal",
  "DressQueen",
  "MahjongLink3D",
  "MergeAndDefense",
  "MergeMagicJewellery",
  "PetRun",
  "SkyRunning3D",
  "SuperGolf",
  "TowerDefenseX",
  "PandaRescue",
  "FillTheGlass",
  "MagicNumber",
  "PlantBeatZombies",
  "AirHockey3D",
  "MyBowling3D",
  "Chess3D",
  "8BallKing",
  "MyUnicorn",
  "MagicJigsaw",
  "FairyTalesPuzzle",
  "PipePuzzle",
  "SplittingCells",
  "FeedMaster",
  "FinalBattle",
  "SuperDefense",
  "Super2048",
  "BubblePop",
  "RelivedLife",
  "CandyHit",
  "MergeCat",
  "MelodyLink",
  "PuzzleVenture",
  "BrainMaster",
  "AntRun",
  "BombingTime",
  "BlockMaze",
  "HappyTetris",
  "MagicPainter",
  "MatchingCook",
  "ColorBead",
  "ColorSplash",
  "RollingAgent",
  "RushingRover",
];

export const FEATURED_GAMES = ["BoardTheTrain", "JumpSmash", "TrafficRun"];
